name: Delete Netatmo Data

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '0 0 * * *'

jobs:
  DeleteNetatmoData:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Delete Netatmo API
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: 'curl --location --request DELETE "https://netatmo-graph.vercel.app/api/delete" --header "key: $API_KEY"'
