name: Set Netatmo Data

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0/30 * * * *'

jobs:
  SetNetatmoData30min:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Netatmo API
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: 'curl --location --request POST "https://netatmo-graph.vercel.app/api/set" --header "key: $API_KEY"'
